### ISSUE TITLE
The instructions in background image banner-bg.jpg don't work 

### ISSUE THREAD

**Issue by bhavin192** [transtats/transtats.github.io#3]
As this issue mentions https://github.com/transtats/transtats/issues/70
The instructions from [this image](https://github.com/transtats/transtats.github.io/blob/master/img/banner-bg.jpg) will give error.

**Comment by sdp5** [comment]
@bhavin192 Is anything left here?

**Comment by bhavin192** [comment]
Fixed by 06adfa6770c2f
