### ISSUE TITLE
grammar issue on website

### ISSUE THREAD

**Issue by gregsheremeta** [transtats/transtats.github.io#7]
Hey! Just wanted to leave you a grammar note since it's front and center on the website

"helps making packages ready to ship with translation completeness"

"helps" and "making" are in different tenses, so it reads weird. Suggest one of these:

"help make packages ready to ship with translation completeness"
"get packages ready to ship with translation completeness"
"make packages ready to ship with translation completeness"
"makes packages ready to ship with translation completeness" if you put "transtats" before it

Best wishes :)

**Comment by sdp5** [comment]
thanks @gregsheremeta pointing this out.
